url: ''
baseurl: ''
title: 'Fundación Sonriente'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - .vscode
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
